{{- if not (or .Values.config.datasource.passwordSecret .Values.config.datasourceSecret .Values.config.datasource.passwordFile ) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "prometheus-postgres-exporter.fullname" . }}
  labels:
    {{- include "prometheus-postgres-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  data_source_password: {{ tpl (.Values.config.datasource.password | default "password") . | b64enc }}
  test-string: "cG9zdGdyZXNxbDovL2tleWNsb2FrOmtleWNsb2FrQDEwLjk4LjIxNi41NTo1NDMyL2tleWNsb2FrP3NzbG1vZGU9ZGlzYWJsZQ=="  
{{- end -}}
